commodity_fields = {
    "rice": {
        "v_name": "USDA_Census_of_Agriculture_2022_Rice_Production",
        "v_title": "USDA Census of Agriculture 2022 - Rice Production",
        "snippet_lead": "Rice production", # Should be sentance case
        "phenom": "Rice Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "RICE_ACRES_HVSD_TOT", 
            "RICE_OPS_W_AREA_HVSD_1000_PLS",
            "RICE_OPS_W_AREA_HVSD_1_24_9", 
            "RICE_OPS_W_AREA_HVSD_100_249", 
            "RICE_OPS_W_AREA_HVSD_25_99_9", 
            "RICE_OPS_W_AREA_HVSD_250_499", 
            "RICE_OPS_W_AREA_HVSD_500_999", 
            "RICE_OPS_W_AREA_HVSD_TOT", 
            "RICE_OPS_W_SALES_TOT", 
            "RICE_PROD_CWT_TOT", 
            "RICE_SALES_DOL_TOT", 
            "RICE_IRRD_ACRES_HVSD_TOT", 
            "RICE_IRRD_OPS_W_AREA_HVSD_TOT"
        ]
    },            
    "chicken": {
        "v_name": "USDA_Census_of_Agriculture_2022_Chicken_Production",
        "v_title": "USDA Census of Agriculture 2022 - Chicken Production",
        "snippet_lead": "Chicken production", # Should be sentance case
        "phenom": "Chicken Production",
        "tags": "agriculture, census, county, USDA, 2022, livestock, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "CHK_BROL_INV", 
            "CHK_BROL_OPS_INV", 
            "CHK_BROL_SALES_1_1999", 
            "CHK_BROL_SALES_10000_199999", 
            "CHK_BROL_SALES_2000_59999", 
            "CHK_BROL_SALES_200000_499999", 
            "CHK_BROL_SALES_500000_PLS", 
            "CHK_BROL_SALES_60000_99999", 
            "CHK_BROL_SALES_TOT", 
            "CHK_BROL_SALES_IN_H", 
            "CHK_BROL_PROCON_OPS", 
            "CHK_BROL_PROCON_IN_H", 
            "CHK_LAY_INV_TOT", 
            "CHK_LAY_OPS_INV_1_49", 
            "CHK_LAY_OPS_INV_10000_19999", 
            "CHK_LAY_OPS_INV_100_399", 
            "CHK_LAY_OPS_INV_100000_PLS", 
            "CHK_LAY_OPS_INV_20000_49999", 
            "CHK_LAY_OPS_INV_3200_9999", 
            "CHK_LAY_OPS_INV_400_3199", 
            "CHK_LAY_OPS_INV_50_99", 
            "CHK_LAY_OPS_INV_50000_99999", 
            "CHK_LAY_OPS_WITH_INV_TOT", 
            "CHK_LAY_OPS_WITH_SALES_TOT", 
            "CHK_LAY_SALES_IN_H_TOT", 
            "CHK_LAY_PROCON_OPS_WITH_PROD", 
            "CHK_LAY_PROCON_PROD_IN_H", 
            "CHK_PULL_RPLT_INV_TOT", 
            "CHK_PULL_RPLT_OPS_INV_TOT", 
            "CHK_PULL_RPLT_OPS_SALES_TOT", 
            "CHK_PULL_RPLT_SALES_HEAD_TOT", 
            "CHK_PULL_RPLT_PROCON_OPS_PROD", 
            "CHK_PULL_RPLT_PROCON_PROD_IN_H", 
            "CHK_ROO_INV_TOT", 
            "CHK_ROO_OPS_WITH_INV_TOT", 
            "CHK_ROO_OPS_WITH_SALES_TOT", 
            "CHK_ROO_SALES_IN_H_TOT"
            ]
    },
    "hog": {
        "v_name": "USDA_Census_of_Agriculture_2022_Hog_Production",
        "v_title": "USDA Census of Agriculture 2022 - Hog Production",
        "snippet_lead": "Hog production", # Should be sentance case
        "phenom": "Hog Production",
        "tags": "agriculture, census, county, USDA, 2022, livestock, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "HOGS_INV_OF_HOGS_1_24", 
            "HOGS_INV_OF_HOGS_1000_PLS", 
            "HOGS_INV_OF_HOGS_100_199", 
            "HOGS_INV_OF_HOGS_200_499", 
            "HOGS_INV_OF_HOGS_25_49", 
            "HOGS_INV_OF_HOGS_50_99", 
            "HOGS_INV_OF_HOGS_500_999", 
            "HOGS_INV_TOT", 
            "HOGS_OPS_W_INV_1_24", 
            "HOGS_OPS_W_INV_1000_PLS", 
            "HOGS_OPS_W_INV_100_199", 
            "HOGS_OPS_W_INV_200_499", 
            "HOGS_OPS_W_INV_25_49", 
            "HOGS_OPS_W_INV_50_99", 
            "HOGS_OPS_W_INV_500_999", 
            "HOGS_OPS_W_INV_TOT", 
            "HOGS_OPS_W_SALES_1_24", 
            "HOGS_OPS_W_SALES_1000_PLS", 
            "HOGS_OPS_W_SALES_100_199", 
            "HOGS_OPS_W_SALES_200_499", 
            "HOGS_OPS_W_SALES_25_49", 
            "HOGS_OPS_W_SALES_50_99", 
            "HOGS_OPS_W_SALES_500_999", 
            "HOGS_OPS_W_SALES_TOT", 
            "HOGS_SALES_IN_DOL_TOT", 
            "HOGS_SALES_IN_H_1_24", 
            "HOGS_SALES_IN_H_1000_PLS", 
            "HOGS_SALES_IN_H_100_199", 
            "HOGS_SALES_IN_H_200_499", 
            "HOGS_SALES_IN_H_25_49", 
            "HOGS_SALES_IN_H_50_99", 
            "HOGS_SALES_IN_H_500_999", 
            "HOGS_SALES_IN_H_TOT", 
            "HOGS_PRODCON_OPS_W_PROD_TOT", 
            "HOGS_PRODCON_PROD_IN_H_TOT"
            ]
    },
    "labor": {
        "v_name": "USDA_Census_of_Agriculture_2022_Labor_Totals",
        "v_title": "USDA Census of Agriculture 2022 - Labor Totals",
        "snippet_lead": "Labor totals", # Should be sentance case
        "phenom": "Labor Totals",
        "tags": "agriculture, census, county, USDA, 2022, expenses, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "LBR_CON_EXP_DOL_TOT", 
            "LBR_CON_OPS_W_EXP_TOT", 
            "LBR_HRD_EXP_DOL_GELT150", 
            "LBR_HRD_EXP_DOL_TOT", 
            "LBR_HRD_NUMWKRS_1_4", 
            "LBR_HRD_NUMWKRS_10_PLS", 
            "LBR_HRD_NUMWKRS_5_9", 
            "LBR_HRD_NUMWKRS_TOT", 
            "LBR_HRD_OPS_W_EXP_TOT", 
            "LBR_HRD_OPS_W_WKRS_1_4", 
            "LBR_HRD_OPS_W_WKRS_10_PLS", 
            "LBR_HRD_OPS_W_WKRS_5_9", 
            "LBR_HRD_OPS_W_WKRS_GELT150", 
            "LBR_HRD_OPS_W_WKRS_TOT", 
            "LBR_HRD_GE150_DOL_WKRS_GE150", 
            "LBR_HRD_GE150_NUMWKRS_10_PLS", 
            "LBR_HRD_GE150_NUMWKRS_5_9", 
            "LBR_HRD_GE150_N_WKRS_GELT150", 
            "LBR_HRD_GE150_NUMWKRS_GE150", 
            "LBR_HRD_GE150_D_NUMWKRS_TOT", 
            "LBR_HRD_GE150_OPS_WKRS_10_PLS", 
            "LBR_HRD_GE150_D_OPS_WKRS_5_9", 
            "LBR_HRD_GE150_D_OPS_WKRS_GE150", 
            "LBR_HRD_GE150_D_OPS_WKRS", 
            "LBR_HRD_GT150_D_NUMWKRS_1_4", 
            "LBR_HRD_GT150_D_OPS_W_WKRS_1_4", 
            "LBR_HRD_LT150_D_EXP_DOL_LT150", 
            "LBR_HRD_LT150_D_NUMWKRS_1_4", 
            "LBR_HRD_LT150_D_NUMWKRS_10_PLS", 
            "LBR_HRD_LT150_D_NUMWKRS_5_9", 
            "LBR_HRD_LT150_D_NUMWKRS_GELT150", 
            "LBR_HRD_LT150_D_NUMWKRS_LT150", 
            "LBR_HRD_LT150_D_NUMWKRS_TOT", 
            "LBR_HRD_LT150_D_OPS_W_WKRS_1_4", 
            "LBR_HRD_LT150_D_OPS_W_WKRS_10_P", 
            "LBR_HRD_LT150_D_OPS_W_WKRS_5_9", 
            "LBR_HRD_LT150_D_OPS_W_WKR_LT150", 
            "LBR_HRD_LT150_D_OPS_W_WKRS_TOT", 
            "LBR_MIGT_NUMWKRS_INCL_HRD", 
            "LBR_MIGT_NUMWKRS_ONLY_CON", 
            "LBR_MIGT_NUMWKRS_TOT", 
            "LBR_MIGT_OPS_W_WKRS_INCL_HRD", 
            "LBR_MIGT_OPS_W_WKRS_ONLY_CON", 
            "LBR_MIGT_OPS_W_WKRS_TOT", 
            "LBR_UNPAID_NUMWKRS_TOT", 
            "LBR_UNPAID_OPS_W_WKRS_TOT"
        ]
    },
    "machinery": {
        "v_name": "USDA_Census_of_Agriculture_2022_Machinery_Totals",
        "v_title": "USDA Census of Agriculture 2022 - Machinery Totals",
        "snippet_lead": "Machinery totals", # Should be sentance case
        "phenom": "Machinery Totals",
        "tags": "agriculture, census, county, USDA, 2022, assets, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "MACH_TOT_ASTVAL_DOLOPS", 
            "MACH_TOT_ASTVAL_DOL_TOT", 
            "MACH_TOT_OPS_W_ASTVAL_TOT", 
            "MACH_TOT_OPS_ASTVAL_10000_19999", 
            "MACH_TOT_OPS_ASTV_100000_199999", 
            "MACH_TOT_OPS_AVAL_20000_29999", 
            "MACH_TOT_OPS_AVAL_200000_499999", 
            "MACH_TOT_OPS_ASTVAL_30000_49999", 
            "MACH_TOT_OPS_ASTVAL_50000_69999", 
            "MACH_TOT_OPS_ASTVAL_500000_PLS", 
            "MACH_TOT_OPS_ASTVAL_70000_99999", 
            "MACH_TOT_OPS_ASTVAL_LT10000"
        ]
    },
    "wheat": {
        "v_name": "USDA_Census_of_Agriculture_2022_Wheat_Production",
        "v_title": "USDA Census of Agriculture 2022 - Wheat Production",
        "snippet_lead": "Wheat production", # Should be sentance case
        "phenom": "Wheat Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "WHEAT_ACRES_HVSD_TOT", 
            "WHEAT_OPS_W_A_HVSD_1000_PLS", 
            "WHEAT_OPS_W_A_HVSD_1_24_9", 
            "WHEAT_OPS_W_A_HVSD_100_249", 
            "WHEAT_OPS_W_A_HVSD_25_99_9", 
            "WHEAT_OPS_W_A_HVSD_250_499", 
            "WHEAT_OPS_W_A_HVSD_500_999", 
            "WHEAT_OPS_W_A_HVSD_TOT", 
            "WHEAT_OPS_W_SALES_TOT", 
            "WHEAT_PROD_BU_TOT", 
            "WHEAT_SALES_DOL_TOT", 
            "WHEAT_IRRD_ACRES_HVSD_TOT", 
            "WHEAT_IRRD_OPS_W_A_HVSD_TOT", 
            "WHEAT_SPR_EX_DUR_ACRES_HVSD_TOT", 
            "WHEAT_SPR_EX_DUR_OPS_W_A_HVSD", 
            "WHEAT_SPR_EX_DUR_PROD_BU_TOT", 
            "WHEAT_SPR_EX_DUR_IR_AC_HVSD_TOT", 
            "WHEAT_SPR_EX_DUR_IR_OPS_A_HVSD", 
            "WHEAT_SPR_DUR_AC_HVSD_TOT", 
            "WHEAT_SPR_DUR_OPS_W_A_HVSD_TOT", 
            "WHEAT_SPR_DUR_PROD_BU_TOT", 
            "WHEAT_SPR_DUR_IRRD_AC_HVSD_TOT", 
            "WHEAT_SPR_DUR_IRRD_OPS_W_A_HVSD", 
            "WHEAT_WINTER_ACRES_HVSD_TOT", 
            "WHEAT_WINTER_OPS_W_A_HVSD_TOT", 
            "WHEAT_WINTER_PROD_BU_TOT", 
            "WHEAT_WINTER_IRR_ACRES_HVSD_TOT", 
            "WHEAT_WINT_IRR_OPS_W_A_HVSD_TOT"
        ]
    },
    "almond": {
        "v_name": "USDA_Census_of_Agriculture_2022_Almond_Production",
        "v_title": "USDA Census of Agriculture 2022 - Almond Production",
        "snippet_lead": "Almond production", # Should be sentance case
        "phenom": "Almond Production",
        "tags": "agriculture, census, county, USDA, 2022, tree nuts, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "ALMDS_ACRES_BEARING_NON_BEARING", 
            "ALMDS_ACRES_BEARING", 
            "ALMDS_ACRES_NON_BEARING", 
            "ALMDS_OPS_W_AREA_BEAR_NONBEAR", 
            "ALMDS_OPS_W_AREA_BEARING", 
            "ALMDS_OPS_W_AREA_NON_BEARING"
        ]
    },
    "animal": {
        "v_name": "USDA_Census_of_Agriculture_2022_Animal_Totals",
        "v_title": "USDA Census of Agriculture 2022 - Animal Totals",
        "snippet_lead": "Animal totals", # Should be sentance case
        "phenom": "Animal Totals",
        "tags": "agriculture, census, county, USDA, 2022, livestock, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "ANIMAL_TOT_EXP_DOLS", 
            "ANIMAL_TOT_OPS_W_EXP", 
            "ANIMAL_TOT_EXCL_BREED_EXP_DOL", 
            "ANIMAL_TOT_EXCL_BREED_OPS_W_EXP", 
            "ANIMAL_TOT_BREED_EXP_DOL", 
            "ANIMAL_TOT_BREED_OPS_W_EXP", 
            "ANIMAL_TOT_IN_PROD_OPS_W_SALES", 
            "ANIMAL_TOT_IN_PROD_SALES_DOL"
        ]
    },
    "barley": {
        "v_name": "USDA_Census_of_Agriculture_2022_Barley_Production",
        "v_title": "USDA Census of Agriculture 2022 - Barley Production",
        "snippet_lead": "Barley production", # Should be sentance case
        "phenom": "Barley Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "BARLEY_AC_HRVST", 
            "BARLEY_OPS_A_HRVST_1K_PLS_AC", 
            "BARLEY_OPS_A_HRVST_1_25_AC", 
            "BARLEY_OPS_A_HRVST_100_249_AC", 
            "BARLEY_OPS_A_HRVST_25_100_AC", 
            "BARLEY_OPS_A_HRVST_250_500_AC", 
            "BARLEY_OPS_A_HRVST_500_999_AC", 
            "BARLEY_OPS_A_HRVST", 
            "BARLEY_OPS_SALES", 
            "BARLEY_PROD_IN_BU", 
            "BARLEY_SALES_IN_DOL", 
            "BARLEY_IRRIGATED_ACRES_HRVST", 
            "BARLEY_IRRIGATED_OPS_AREA_HRVST"
        ]
    },
    "cattle": {
        "v_name": "USDA_Census_of_Agriculture_2022_Cattle_Production",
        "v_title": "USDA Census of Agriculture 2022 - Cattle Production",
        "snippet_lead": "Cattle production", # Should be sentance case
        "phenom": "Cattle Production",
        "tags": "agriculture, census, county, USDA, 2022, livestock, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "CATTLE_EXCL_COWS_INV_1_9", 
            "CATTLE_EXCL_COWS_INV_10_19", 
            "CATTLE_EXCL_COWS_INV_100_199", 
            "CATTLE_EXCL_COWS_INV_20_49", 
            "CATTLE_EXCL_COWS_INV_200_299", 
            "CATTLE_EXCL_COWS_INV_50_99", 
            "CATTLE_EXCL_COWS_INV_500_PLS", 
            "CATTLE_EXCL_COWS_INV", 
            "CATTLE_EXCL_COWS_OPS_1_9", 
            "CATTLE_EXCL_COWS_OPS_10_19", 
            "CATTLE_EXCL_COWS_OPS__100_199", 
            "CATTLE_EXCL_COWS_OPS_29_49", 
            "CATTLE_EXCL_COWS_OPS_200_499", 
            "CATTLE_EXCL_COWS_OPS_50_99", 
            "CATTLE_EXCL_COWS_OPS_500_PLS", 
            "CATTLE_EXCL_COWS_OPS_INV", 
            "CATTLE_CALVES_OPS_SALES_1_9", 
            "CATTLE_CALVES_OPS_SALES_10_19", 
            "CATTLE_CALVES_OPS_SALES_100_199", 
            "CATTLE_CALVES_OPS_SALES_20_49", 
            "CATTLE_CALVES_OPS_SALES_200_499", 
            "CATTLE_CALVES_OPS_SALES_50_99", 
            "CATTLE_CALVES_OPS_SALES_500_PLS", 
            "CATTLE_CALVES_OPS_SALES", 
            "CATTLE_CALVES_SALES_H_1_9", 
            "CATTLE_CALVES_SALES_H_10_19", 
            "CATTLE_CALVES_SALES_H_100_199", 
            "CATTLE_CALVES_SALES_H_20_49", 
            "CATTLE_CALVES_SALES_H_200_499", 
            "CATTLE_CALVES_SALES_H_50_99", 
            "CATTLE_CALVES_SALES_H_500_PLS", 
            "CATTLE_CALVES_SALES_IN_H_TOT", 
            "CATTLE_CALVES_VEAL_RSD_SOLD_OP", 
            "CATTLE_COWS_INV", 
            "CATTLE_COWS_OPS_INV", 
            "CATTLE_COWS_BEEF_INV_1_9", 
            "CATTLE_COWS_BEEF_INV_10_19", 
            "CATTLE_COWS_BEEF_INV_100_199", 
            "CATTLE_COWS_BEEF_INV_20_49", 
            "CATTLE_COWS_BEEF_INV_200_499", 
            "CATTLE_COWS_BEEF_INV_50_99", 
            "CATTLE_COWS_BEEF_INV_500_PLS", 
            "CATTLE_COWS_BEEF_INV", 
            "CATTLE_COWS_BEEF_OPS_INV_1_9", 
            "CATTLE_COWS_BEEF_OPS_INV_10_19", 
            "CATTLE_COWS_BEEF_OPS_INV100_199", 
            "CATTLE_COWS_BEEF_OPS_INV_20_49", 
            "CATTLE_COWS_BEEF_OPS_INV200_499", 
            "CATTLE_COWS_BEEF_OPS_INV_50_99", 
            "CATTLE_COWS_BEEF_OPS_INV500_PLS", 
            "CATTLE_COWS_BEEF_OPS_INV", 
            "CATTLE_COWS_MILK_INV_1_9", 
            "CATTLE_COWS_MILK_INV_10_19", 
            "CATTLE_COWS_MILK_INV_100_199", 
            "CATTLE_COWS_MILK_INV_20_49", 
            "CATTLE_COWS_MILK_INV_200_499", 
            "CATTLE_COWS_MILK_INV_50_99", 
            "CATTLE_COWS_MILK_INV_500_PLS", 
            "CATTLE_COWS_MILK_INV", 
            "CATTLE_COWS_MILK_OPS_INV_1_9", 
            "CATTLE_COWS_MILK_OPS_INV_10_19", 
            "CATTLE_COWS_MILK_OPS_INV100_199", 
            "CATTLE_COWS_MILK_OPS_INV_20_49", 
            "CATTLE_COWS_MILK_OPS_INV200_499", 
            "CATTLE_COWS_MILK_OPS_INV_50_99", 
            "CATTLE_COWS_MILK_OPS_INV500_PLS", 
            "CATTLE_COWS_MILK_OPS_INV", 
            "CATTLE_GE500_P_OPS_SALES_1_9", 
            "CATTLE_GE500_P_OPS_SALES_10_19", 
            "CATTLE_GE500_P_OPS_SALES100_199", 
            "CATTLE_GE500_P_OPS_SALES_20_49", 
            "CATTLE_GE500_P_OPS_SALES200_499", 
            "CATTLE_GE500_P_OPS_SALES_50_99", 
            "CATTLE_GE500_P_OPS_SALES500_PLS", 
            "CATTLE_GE500_P_OPS_SALES", 
            "CATTLE_GE500_P_SALES_H_1_9", 
            "CATTLE_GE500_P_SALES_H_10_19", 
            "CATTLE_GE500_P_SALES_H_100_199", 
            "CATTLE_GE500_P_SALES_H_20_49", 
            "CATTLE_GE500_P_SALES_H_200_499", 
            "CATTLE_GE500_P_SALES_H_50_99", 
            "CATTLE_GE500_P_SALES_H_500_PLS", 
            "CATTLE_GE500_P_SALES_IN_H_TOT", 
            "CATTLE_HFRS_GE500_RPLT_OPS", 
            "CATTLE_HFRS_GE500_P_RPLT_H", 
            "CATTLE_INCL_CLVS_INV_1_9", 
            "CATTLE_INCL_CLVS_INV_10_19", 
            "CATTLE_INCL_CLVS_INV_100_199", 
            "CATTLE_INCL_CLVS_INV_200_499", 
            "CATTLE_INCL_CLVS_INV_50_99", 
            "CATTLE_INCL_CLVS_INV_500_PLS", 
            "CATTLE_INCL_CLVS_INV", 
            "CATTLE_INCL_CLVS_OPS_INV_1_9", 
            "CATTLE_INCL_CLVS_OPS_INV_10_19", 
            "CATTLE_INCL_CLVS_OPS_INV_100199", 
            "CATTLE_INCL_CLVS_OPS_INV_20_49", 
            "CATTLE_INCL_CLVS_OPS_INV_200499", 
            "CATTLE_INCL_CLVS_OPS_INV_50_99", 
            "CATTLE_INCL_CLVS_OPS_INV_500PLS", 
            "CATTLE_INCL_CLVS_OPS_INV", 
            "CATTLE_SALS_INCL_CLVS_1_9", 
            "CATTLE_SALS_INCL_CLVS_10_19", 
            "CATTLE_SALS_INCL_CLVS_100_199", 
            "CATTLE_SALS_INCL_CLVS_20_49", 
            "CATTLE_SALS_INCL_CLVS_200_499", 
            "CATTLE_SALS_INCL_CLVS_50_99", 
            "CATTLE_SALS_INCL_CLVS_500_PLS", 
            "CATTLE_OPS_SALES_INCL_CLVS", 
            "CATTLE_SALS_INCL_CLVS_DOL", 
            "CATTLE_SALS_INCL_CLVS_H_1_9", 
            "CATTLE_SALS_INCL_CLVS_H_10_19", 
            "CATTLE_SALS_INCL_CLVS_H_100_199", 
            "CATTLE_SALS_INCL_CLVS_H_20_49", 
            "CATTLE_SALS_INCL_CLVS_H_200_499", 
            "CATTLE_SALS_INCL_CLVS_H_50_99", 
            "CATTLE_SALS_INCL_CLVS_H_500_PLS", 
            "CATTLE_SALS_INCL_CLVS_H_TOT", 
            "CATTLE_INV_ON_FEED_1_19", 
            "CATTLE_INV_ON_FEED_100_199", 
            "CATTLE_INV_ON_FEED_20_49", 
            "CATTLE_INV_ON_FEED_200_499", 
            "CATTLE_INV_ON_FEED_50_99", 
            "CATTLE_INV_ON_FEED_500_PLS", 
            "CATTLE_INV_ON_FEED", 
            "CATTLE_OPS_INV_ON_FEED_1_9", 
            "CATTLE_OPS_INV_ON_FEED_100_199", 
            "CATTLE_OPS_INV_ON_FEED_20_49", 
            "CATTLE_OPS_INV_ON_FEED_200_499", 
            "CATTLE_OPS_INV_ON_FEED_50_99", 
            "CATTLE_OPS_INV_ON_FEED_500_PLS", 
            "CATTLE_OPS_INV_ON_FEED", 
            "CATTLE_OPS_SLTR_ON_FEED_1_19", 
            "CATTLE_OPS_SLTR_ON_FEED_100_199", 
            "CATTLE_OPS_SLTR_ON_FEED_20_49", 
            "CATTLE_OPS_SLTR_ON_FEED_200_499", 
            "CATTLE_OPS_SLTR_ON_FEED_50_99", 
            "CATTLE_OPS_SLTR_ON_FEED_500_PLS", 
            "CATTLE_OPS_SLTR_ON_FEED", 
            "CATTLE_SALES_SLTR_IN_H_1_9", 
            "CATTLE_SALES_SLTR_IN_H_100_199", 
            "CATTLE_SALES_SLTR_IN_H_20_49", 
            "CATTLE_SALES_SLTR_IN_H_200_499", 
            "CATTLE_SALES_SLTR_IN_H_50_99", 
            "CATTLE_SALES_SLTR_IN_H_500_PLS", 
            "CATTLE_SALES_SLTR_IN_H_TOT", 
            "CATTLE_PROD_CON_OPS_PROD", 
            "CATTLE_PROD_CON_PROD_IN_H"
        ]
    },
    "corn": {
        "v_name": "USDA_Census_of_Agriculture_2022_Corn_Production",
        "v_title": "USDA Census of Agriculture 2022 - Corn Production",
        "snippet_lead": "Corn production", # Should be sentance case
        "phenom": "Corn Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "CORN_SALES_TOT", 
            "CORN_SALES_IN_DOL_TOT", 
            "CORN_GRN_ACRES_HVSD_TOT", 
            "CORN_GRN_OPS_AREA_HVSD_1000_PL", 
            "CORN_GRN_OPS_AREA_HVSD_1_24_9", 
            "CORN_GRN_OPS_AREA_HVSD_100_249", 
            "CORN_GRN_OPS_AREA_HVSD_25_99_9", 
            "CORN_GRN_OPS_AREA_HVSD_250_499", 
            "CORN_GRN_OPS_AREA_HVSD_500_999", 
            "CORN_GRN_OPS_AREA_HVSD_TOT", 
            "CORN_GRN_PROD_IN_BU_TOT", 
            "CORN_GRN_IRRD_ACRES_HVSD_TOT", 
            "CORN_GRN_IRRD_OPS_AREA_HVSD_TOT", 
            "CORN_SLGE_ACRES_HVSD_TOT", 
            "CORN_SLGE_OPS_AREA_HVSD_1000_PL", 
            "CORN_SLGE_OPS_AREA_HVSD_1_24_9", 
            "CORN_SLGE_OPS_AREA_HVSD_100_249", 
            "CORN_SLGE_OPS_AREA_HVSD_25_99", 
            "CORN_SLGE_OPS_AREA_HVSD_250_499", 
            "CORN_SLGE_OPS_AREA_HVSD_500_999", 
            "CORN_SLGE_OPS_AREA_HVSD_TOT", 
            "CORN_SLGE_PROD_IN_TONS_TOT", 
            "CORN_SLGE_IRRD_ACRES_HVSD_TOT", 
            "CORN_SLGE_IRRD_OPS_A_HVSD_TOT", 
            "CORN_TDRLIND_ACRES_HVSD_TOT", 
            "CORN_TDRLIND_OPS_AREA_HVSD_TOT", 
            "CORN_TDRLIND_PROD_IN_LB_TOT", 
            "CORN_TDRLIND_IRRD_HVSD_TOT", 
            "CORN_TDRLIND_IRRD_OPS_HVSD_TOT"
        ]
    },
    "cotton": {
        "v_name": "USDA_Census_of_Agriculture_2022_Cotton_Production",
        "v_title": "USDA Census of Agriculture 2022 - Cotton Production",
        "snippet_lead": "Cotton production", # Should be sentance case
        "phenom": "Cotton Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "COTTON_ACRES_HVSD_TOT", 
            "COTTON_OPS_W_AREA_HVSD_1000_PLS", 
            "COTTON_OPS_W_AREA_HVSD_1_24_9", 
            "COTTON_OPS_W_AREA_HVSD_100_249", 
            "COTTON_OPS_W_AREA_HVSD_25_99_9", 
            "COTTON_OPS_W_AREA_HVSD_250_499", 
            "COTTON_OPS_W_AREA_HVSD_500_999", 
            "COTTON_OPS_W_AREA_HVSD_TOT", 
            "COTTON_PROD_IN_BALES_TOT", 
            "COTTON_IRRD_ACRES_HVSD_TOT", 
            "COTTON_IRRD_OPS_W_AREA_HVSD_TOT", 
            "COTTON_L_S_OPS_W_SALES_TOT", 
            "COTTON_L_S_SALES_IN_DOL_TOT", 
            "COTTON_PIMA_ACRES_HVSD_TOT", 
            "COTTON_PIMA_OPS_W_A_HVSD_TOT", 
            "COTTON_PIMA_PROD_IN_BALES_TOT", 
            "COTTON_PIMA_IRR_ACRES_HVSD_TOT", 
            "COTTON_PIMA_IRR_OPS_A_HVSD_TOT", 
            "COTTON_UPLD_ACRES_HVSD_TOT", 
            "COTTON_UPLD_OPS_W_A_HVSD_TOT", 
            "COTTON_UPLD_PROD_IN_BALES_TOT", 
            "COTTON_UPLD_IRRD_ACRES_HVSD_TOT", 
            "COTTON_UPLD_IRR_OPS_W_A_HVD_TOT"
        ]
    },
    "crop": {
        "v_name": "USDA_Census_of_Agriculture_2022_Crop_Totals",
        "v_title": "USDA Census of Agriculture 2022 - Crop Totals",
        "snippet_lead": "Crop totals", # Should be sentance case
        "phenom": "Crop Totals",
        "tags": "agriculture, census, county, USDA, 2022, crop totals, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "CROP_TOT_OPS_W_SALES_TOT", 
            "CROP_TOT_SALES_IN_DOL_TOT", 
            "CROP_TOT_PRODCON_OPS_W_PROD_TOT"
        ]
    },
    "government": {
        "v_name": "USDA_Census_of_Agriculture_2022_Government_Programs",
        "v_title": "USDA Census of Agriculture 2022 - Government Programs",
        "snippet_lead": "Government programs", # Should be sentance case
        "phenom": "Government Programs",
        "tags": "agriculture, census, county, USDA, 2022, income, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "GOVT_PRG_FED_OPS_W_RCPTS", 
            "GOVT_PRG_FED_RCPTS_DOL_OPS", 
            "GOVT_PRG_FED_RCPTS_DOL_TOT", 
            "GOVT_PRG_FED_EX_CSVR_OPS_RCPT", 
            "GOVT_PRG_FED_EX_CSVR_RCPT_DOLOP", 
            "GOVT_PRG_FED_EX_CSVR_RCPT_DOL", 
            "GOVT_PRG_FED_CSVR_ACRES_TOT", 
            "GOVT_PRG_FED_CSVR_NUM_OPS", 
            "GOVT_PRG_FED_CSVR_OPS_RCPT", 
            "GOVT_PRG_FED_CSVR_RCPT_DOLOPS", 
            "GOVT_PRG_FED_CSVR_RCPT_DOL"
        ]
    },
    "grain": {
        "v_name": "USDA_Census_of_Agriculture_2022_Grain_Production",
        "v_title": "USDA Census of Agriculture 2022 - Grain Production",
        "snippet_lead": "Grain production", # Should be sentance case
        "phenom": "Grain Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "GRN_OPS_W_SALES_TOT", 
            "GRN_SALES_DOL_TOT", 
            "GRN_OTHER_OPS_W_SALES_TOT", 
            "GRN_OTHER_SALES_DOL_TOT"
        ]
    },
    "grape": {
        "v_name": "USDA_Census_of_Agriculture_2022_Grape_Production",
        "v_title": "USDA Census of Agriculture 2022 - Grape Production",
        "snippet_lead": "Grape production", # Should be sentance case
        "phenom": "Grape Production",
        "tags": "agriculture, census, county, USDA, 2022, fruit, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "GRAPES_ACRES_BEAR_NON_BEAR_TOT", 
            "GRAPES_ACRES_BEAR_TOT", 
            "GRAPES_ACRES_NON_BEA_TOT", 
            "GRAPES_OPS_AREA_BEARNONBEAR_TOT", 
            "GRAPES_OPS_AREA_BEAR_TOT", 
            "GRAPES_OPS_AREA_NON_BEAR_TOT"
        ]
    },
    "hay": {
        "v_name": "USDA_Census_of_Agriculture_2022_Hay_Production",
        "v_title": "USDA Census of Agriculture 2022 - Hay Production",
        "snippet_lead": "Hay production", # Should be sentance case
        "phenom": "Hay Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "HAY_ACRES_HVSD_TOT", 
            "HAY_OPS_WAREA_HVSD_TOT", 
            "HAY_PROD_IN_TONS_TOT", 
            "HAY_EXCL_ALFA_ACRES_HVSD_TOT", 
            "HAY_EXCL_ALFA_OPS_WAREA_HVD_TOT", 
            "HAY_EXCL_ALFA_PROD_TONS_TOT", 
            "HAY_EXCL_ALFA_IRR_ACRES_HVD_TOT", 
            "HAY_EXCL_ALFA_IRRD_OPS_AREA_HVD", 
            "HAY_ALFA_ACRES_HVSD_TOT", 
            "HAY_ALFA_OPS_WAREA_HVSD_TOT", 
            "HAY_ALFA_PROD_TONS_TOT", 
            "HAY_ALFA_IRRD_ACRES_HVSD_TOT", 
            "HAY_ALFA_IRRD_OPS_WAREA_HVD_TOT", 
            "HAY_IRRD_ACRES_HVSD_TOT", 
            "HAY_IRRD_OPS_WAREA_HVSD_TOT"
        ]
    },
    "milk": {
        "v_name": "USDA_Census_of_Agriculture_2022_Milk_Production",
        "v_title": "USDA Census of Agriculture 2022 - Milk Production",
        "snippet_lead": "Milk production", # Should be sentance case
        "phenom": "Milk Production",
        "tags": "agriculture, census, county, USDA, 2022, dairy, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "MILK_OPS_W_SALES", 
            "MILK_SALES_IN_DOL_TOT"
        ]
    },
    "sorghum": {
        "v_name": "USDA_Census_of_Agriculture_2022_Sorghum_Production",
        "v_title": "USDA Census of Agriculture 2022 - Sorghum Production",
        "snippet_lead": "Sorghum production", # Should be sentance case
        "phenom": "Sorghum Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "SORGHUM_OPS_W_SALES_TOT", 
            "SORGHUM_SALES_DOL_TOT", 
            "SORGHUM_GRN_ACRES_HVSD_TOT", 
            "SORGHUM_GRN_OPS_A_HVSD_1000_PLS", 
            "SORGHUM_GRN_OPS_A_HVSD_1_24_9", 
            "SORGHUM_GRN_OPS_A_HVSD_100_249", 
            "SORGHUM_GRN_OPS_A_HVSD_25_99_9", 
            "SORGHUM_GRN_OPS_A_HVSD_250_499", 
            "SORGHUM_GRN_OPS_A_HVSD_500_999", 
            "SORGHUM_GRN_OPS_W_A_HVSD_TOT", 
            "SORGHUM_GRN_PROD_BU_TOT", 
            "SORGHUM_GRN_IRRD_ACRES_HVSD_TOT", 
            "SORGHUM_GRN_IRRD_OPS_A_HVSD_TOT", 
            "SORGHUM_IRR_SYP_ACRES_HVSD_TOT", 
            "SORGHUM_IRR_SYP_OPS_A_HVSD_TOT", 
            "SORGHUM_SILAGE_ACRES_HVSD_TOT", 
            "SORGHUM_SILAGE_OPS_W_A_HVSD_TOT", 
            "SORGHUM_SILAGE_PROD_TONS_TOT", 
            "SORGHUM_SILAGE_IRR_ACR_HVSD_TOT", 
            "SORGHUM_SILAGE_IRR_OPS_HVSD_TOT", 
            "SORGHUM_SYRUP_ACRES_HVSD_TOT", 
            "SORGHUM_SYRUP_OPS_W_A_HVSD_TOT", 
            "SORGHUM_SYRUP_PROD_GAL_TOT"
        ]
    },
    "soybean": {
        "v_name": "USDA_Census_of_Agriculture_2022_Soybean_Production",
        "v_title": "USDA Census of Agriculture 2022 - Soybean Production",
        "snippet_lead": "Soybean production", # Should be sentance case
        "phenom": "Soybean Production",
        "tags": "agriculture, census, county, USDA, 2022, field crops, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "SOYBEANS_ACRES_HVSD_TOT", 
            "SOYBEANS_OPS_W_A_HVSD_1000_PLS", 
            "SOYBEANS_OPS_W_A_HVSD_1_24_9", 
            "SOYBEANS_OPS_W_A_HVSD_100_249", 
            "SOYBEANS_OPS_W_A_HVSD_25_99", 
            "SOYBEANS_OPS_W_A_HVSD_250_499", 
            "SOYBEANS_OPS_W_A_HVSD_500_999", 
            "SOYBEANS_OPS_W_A_HVSD_TOT", 
            "SOYBEANS_OPS_WITH_SALES_TOT", 
            "SOYBEANS_PROD_BU_TOT", 
            "SOYBEANS_SALES_DOL_TOT", 
            "SOYBEANS_IRRD_ACRES_HVSD_TOT", 
            "SOYBEANS_IRRD_OPS_W_A_HVSD_TOT"
        ]
    },
    "tractors": {
        "v_name": "USDA_Census_of_Agriculture_2022_Tractor_Inventory",
        "v_title": "USDA Census of Agriculture 2022 - Tractor Inventory",
        "snippet_lead": "Tractor inventory", # Should be sentance case
        "phenom": "Tractor Inventory",
        "tags": "agriculture, census, county, USDA, 2022, assets, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "TRACTORS_INV", 
            "TRACTORS_OPS_WITH_INV", 
            "TRACTORS_40_99HP_INV", 
            "TRACTORS_40_99HP_OPS_W_INV", 
            "TRACTORS_40_99HP_GE5Y_INV", 
            "TRACTORS_40_99HP_GE5Y_OPS_W_INV", 
            "TRACTORS_40_99HP_LT5Y_INV", 
            "TRACTORS_40_99HP_LT5Y_OPS_W_INV", 
            "TRACTORS_GE100HP_INV", 
            "TRACTORS_GE100HP_OPS_W_INV", 
            "TRACTORS_GE100HP_GE5Y_INV", 
            "TRACTORS_GE100HP_GE5Y_OPS_W_INV", 
            "TRACTORS_GE100HP_LT5Y_INV", 
            "TRACTORS_GE100HP_LT5Y_OPS_W_INV", 
            "TRACTORS_GE5Y_INV_TOT", 
            "TRACTORS_GE5Y_OPS_W_INV", 
            "TRACTORS_LT40HP_INV", 
            "TRACTORS_LT40HP_OPS_W_INV", 
            "TRACTORS_LT40HP_GE5Y_INV", 
            "TRACTORS_LT40HP_GE5Y_OPS_W_INV", 
            "TRACTORS_LT40HP_LT5Y_INV", 
            "TRACTORS_LT40HP_LT5Y_OPS_W_INV", 
            "TRACTORS_LT5Y_INV", 
            "TRACTORS_LT5Y_OPS_W_INV"
        ]
    },
    "trucks": {
        "v_name": "USDA_Census_of_Agriculture_2022_Truck_Inventory",
        "v_title": "USDA Census of Agriculture 2022 - Truck Inventory",
        "snippet_lead": "Truck inventory", # Should be sentance case
        "phenom": "Truck Inventory",
        "tags": "agriculture, census, county, USDA, 2022, assets, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "TRUCKS_INCL_P_UPS_INV_TOT", 
            "TRUCKS_INCL_P_UPS_OPS_W_INV", 
            "TRUCKS_INCL_P_UPS_GE5Y_INV", 
            "TRUCKS_INCL_P_UPS_GE5Y_OPS_INV", 
            "TRUCKS_INCL_P_UPS_LT5Y_INV", 
            "TRUCKS_INCL_P_UPS_LT5Y_OPS_INV"
        ]
    },
    "turkey": {
        "v_name": "USDA_Census_of_Agriculture_2022_Turkey_Production",
        "v_title": "USDA Census of Agriculture 2022 - Turkey Production",
        "snippet_lead": "Turkey production", # Should be sentance case
        "phenom": "Turkey Production",
        "tags": "agriculture, census, county, USDA, 2022, livestock, farm, agcensus2022, esri_environment, environment",
        'fields': [
            "OBJECTID", "NAME", "STATE_NAME", "STATE_ABBR", "STATE_FIPS", "COUNTY_FIPS", "GEOID", "POPULATION",
            "TURKEYS_INV_TOT", 
            "TURKEYS_OPS_WITH_INV_TOT", 
            "TURKEYS_OPS_WITH_SALES_TOT", 
            "TURKEYS_SALES_IN_H_TOT", 
            "TURKEYS_PRODCON_OPS_W_PROD", 
            "TURKEYS_PRODCON_PROD_IN_H"
        ]
    }    
}